# -*- coding: utf-8 -*-
"""CC_fin_v1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkkRygqQ3KV9TcUZ7W_eivyl9Umy1Y9m
"""

# !pip install PyPDF2 python-pptx transformers reportlab huggingface_hub TTS
import re
from transformers import pipeline
from PyPDF2 import PdfReader
from gtts import gTTS
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
import os

# from transformers import pipeline
# import os
# from PyPDF2 import PdfReader
# import re

# # Function to clean text and remove unwanted phrases
# def clean_text(text, unwanted_phrases=None):
#     if unwanted_phrases is None:
#         unwanted_phrases = ["Discover the world at Leiden University"]
#     for phrase in unwanted_phrases:
#         text = text.replace(phrase, "")
#     return text.strip()

# # Function to remove repeated phrases or sentences
# def remove_repetitions(text):
#     sentences = text.split('. ')
#     seen = set()
#     cleaned_sentences = []
#     for sentence in sentences:
#         normalized_sentence = sentence.strip().lower()
#         if normalized_sentence not in seen:
#             seen.add(normalized_sentence)
#             cleaned_sentences.append(sentence)
#     cleaned_text = '. '.join(cleaned_sentences).strip()
#     cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  # Remove extra spaces
#     cleaned_text = re.sub(r'(\. )+', '. ', cleaned_text)  # Remove repeated periods
#     return cleaned_text

# # Function to extract text from each page of a PDF
# def extract_text_by_page(file_path):
#     reader = PdfReader(file_path)
#     pages = [page.extract_text() for page in reader.pages]
#     return pages

# # Function to summarize text with repetition control
# def summarize_text(text, model_name="facebook/bart-large-cnn"):
#     summarizer = pipeline("summarization", model=model_name, device=0)
#     try:
#         if not text.strip():  # No text detected
#             return "This slide contains no text or mostly images. Please refer to the visuals."
#         summary = summarizer(
#             text,
#             max_length=120,
#             min_length=30,
#             repetition_penalty=2.0,  # Penalize repeated words
#             do_sample=False
#         )
#         return summary[0]["summary_text"]
#     except Exception as e:
#         print(f"Error summarizing text: {e}")
#         return text

# # Function to generate a narrative from the summary
# def generate_narrative(summary, model_name="google/flan-t5-base"):
#     generator = pipeline("text2text-generation", model=model_name, device=0)
#     try:
#         if "no text" in summary.lower():  # Placeholder slide
#             return summary
#         prompt = f"Write a concise and engaging narrative, avoiding repetitions:\n\n{summary}"
#         result = generator(
#             prompt,
#             max_length=200,
#             repetition_penalty=2.0,  # Penalize repetition
#             do_sample=False
#         )
#         return result[0]["generated_text"]
#     except Exception as e:
#         print(f"Error generating narrative: {e}")
#         return summary

# # Main function
# def main():
#     file_path = input("Enter the path to your PDF file: ")

#     # Validate file
#     if not os.path.exists(file_path):
#         print("File not found. Please check the path.")
#         return
#     if not file_path.endswith(".pdf"):
#         print("Unsupported file format! Please provide a PDF file.")
#         return

#     # Extract text from PDF
#     print("Extracting text from PDF...")
#     pages = extract_text_by_page(file_path)

#     if not pages:
#         print("No text extracted from the PDF.")
#         return

#     # Process each page
#     narratives = []
#     for i, page_text in enumerate(pages):
#         print(f"Processing page {i+1}/{len(pages)}...")

#         # Clean text
#         clean_page_text = clean_text(page_text)

#         # Remove repetitions
#         deduplicated_text = remove_repetitions(clean_page_text)

#         # Summarize text
#         summary = summarize_text(deduplicated_text)
#         print(f"  Summary: {summary[:100]}...")

#         # Generate narrative from summary
#         narrative = generate_narrative(summary)
#         print(f"  Narrative: {narrative[:100]}...")

#         # Store results
#         narratives.append(f"Page {i+1}:\n{narrative}\n\n")

#     # Save narratives to file
#     output_file = "out10.txt"
#     with open(output_file, "w", encoding="utf-8") as file:
#         file.writelines(narratives)

#     print(f"Narratives saved to '{output_file}'.")
#     print(f"Preview of first page's narrative:\n{narratives[0]}")

# # Run the main function
# if __name__ == "__main__":
#     main()

# ! pip install gtts
from transformers import pipeline

# ! pip install fpdf

# Function to clean text and remove unwanted phrases
def clean_text(text, unwanted_phrases=None):
    if unwanted_phrases is None:
        unwanted_phrases = [
            "Leiden University",
            "Discover the world",
            "Discover the world at Leiden University",
            "university in the Netherlands",
            "students",
            "campus",
        ]
    for phrase in unwanted_phrases:
        text = re.sub(rf'\b{re.escape(phrase)}\b', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(university|school|campus)\b', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Function to remove repeated phrases or sentences
def remove_repetitions(text):
    sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', text)
    seen = set()
    cleaned_sentences = []
    for sentence in sentences:
        normalized_sentence = sentence.strip().lower()
        if normalized_sentence not in seen:
            seen.add(normalized_sentence)
            cleaned_sentences.append(sentence.strip())
    cleaned_text = ' '.join(cleaned_sentences)
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    return cleaned_text

# Function to summarize text
def summarize_text(text, model_name="facebook/bart-large-cnn"):
    summarizer = pipeline("summarization", model=model_name, device=0)
    try:
        if not text.strip():
            return "This slide contains no text or mostly images. Please refer to the visuals."
        summary = summarizer(
            text,
            max_length=120,
            min_length=30,
            repetition_penalty=2.5,
            do_sample=False
        )
        return summary[0]["summary_text"]
    except Exception as e:
        print(f"Error summarizing text: {e}")
        return text

# Function to generate a narrative
def generate_narrative(summary, model_name="google/flan-t5-base"):
    generator = pipeline("text2text-generation", model=model_name, device=0)
    try:
        if "no text" in summary.lower():
            return summary
        prompt = (
            "You are a lecturer presenting a slide. "
            "Focus exclusively on the content of the slide without considering any references to Leiden University. "
            "Provide a clear, detailed, and engaging explanation. Avoid repeating information or adding unrelated details. "
            "Here is the slide content:\n\n"
            f"{summary}\n\n"
            "Now write an informative and engaging explanation of this slide."
        )
        result = generator(
            prompt,
            max_length=300,
            repetition_penalty=3.0,
            temperature=0.5,
            do_sample=True
        )
        return remove_repetitions(result[0]["generated_text"])
    except Exception as e:
        print(f"Error generating narrative: {e}")
        return summary

# Function to create a combined voice-over file using Google TTS
def generate_combined_voice_over(narratives, output_path="combined_voiceover.mp3"):
    try:
        combined_text = "\n\n".join(narratives)
        tts = gTTS(text=combined_text, lang='en')
        tts.save(output_path)
        print(f"Combined voice-over saved to {output_path}")
    except Exception as e:
        print(f"Error generating voice-over: {e}")

# Function to generate a PDF from narratives
def generate_formatted_pdf(narratives, output_file="Improved_Generated_Narratives.pdf"):
    try:
        c = canvas.Canvas(output_file, pagesize=letter)
        width, height = letter
        margin = 50
        text_width = width - 2 * margin
        text_height = height - 2 * margin
        y_position = height - margin  # Start near the top

        # Title Page
        c.setFont("Helvetica-Bold", 16)
        c.drawCentredString(width / 2, y_position, "Generated Narratives")
        y_position -= 50  # Adjust position for the next content

        for narrative in narratives:
            page_title, page_content = narrative.split(":", 1)
            if y_position < margin:  # If text overflows, create a new page
                c.showPage()
                y_position = height - margin

            # Draw title
            c.setFont("Helvetica-Bold", 14)
            c.drawString(margin, y_position, page_title.strip())
            y_position -= 20

            # Split text into lines manually to fit within the margins
            c.setFont("Helvetica", 12)
            words = page_content.strip().split()
            line = ""
            for word in words:
                if c.stringWidth(line + word + " ", "Helvetica", 12) < text_width:
                    line += word + " "
                else:
                    c.drawString(margin, y_position, line.strip())
                    y_position -= 15  # Adjust line spacing
                    line = word + " "
                    if y_position < margin:  # If text overflows, create a new page
                        c.showPage()
                        y_position = height - margin
            # Draw the last line
            if line.strip():
                c.drawString(margin, y_position, line.strip())
                y_position -= 15

        # Save the PDF
        c.save()
        print(f"Improved formatted PDF saved to '{output_file}'")
    except Exception as e:
        print(f"Error generating improved formatted PDF: {e}")

# Main function
def main():
    file_path = input("Enter the path to your PDF file: ")

    if not os.path.exists(file_path) or not file_path.endswith(".pdf"):
        print("Invalid file. Please provide a valid PDF file.")
        return

    print("Extracting text from PDF...")
    pages = PdfReader(file_path).pages
    if not pages:
        print("No text extracted from the PDF.")
        return

    narratives = []
    for i, page in enumerate(pages[2:], start=3):
        print(f"Processing page {i}/{len(pages)}...")
        raw_text = page.extract_text()
        clean_page_text = clean_text(raw_text)
        deduplicated_text = remove_repetitions(clean_page_text)
        summary = summarize_text(deduplicated_text)
        print(f"  Summary: {summary[:100]}...")
        narrative = generate_narrative(summary)
        print(f"  Narrative: {narrative[:100]}...")
        narratives.append(f"Page {i}:\n{narrative}")

    generate_combined_voice_over(narratives, output_path="combined_voiceover19.mp3")

    output_pdf_file = "Generated_Narratives19.pdf"
    generate_formatted_pdf(narratives, output_pdf_file)

    output_text_file = "out_with_combined_voiceover19.txt"
    with open(output_text_file, "w", encoding="utf-8") as file:
        file.write("\n\n".join(narratives))

    print(f"Narratives saved to '{output_text_file}'.")
    print(f"Preview of first page's narrative:\n{narratives[0]}")

if __name__ == "__main__":
    main()